dist: trusty
sudo: required
group: deprecated-2017Q4
language: python
python: 2.7

branches:
  only:
  - master

cache:
  yarn: true
  directories:
    - "${HOME}/virtualenv/python$(python -c 'import platform; print(platform.python_version())')"
    - "$NODE_DIR"
    - node_modules
    - "${HOME}/google-cloud-sdk"

addons:
  apt:
    update: true
    packages:
      - libxmlsec1-dev
      - libgeoip-dev
  chrome: stable

env:
  global:
    - NODE_ENV=development
    - PIP_DISABLE_PIP_VERSION_CHECK=on
    - PIP_QUIET=1
    - SENTRY_LIGHT_BUILD=1
    - SENTRY_SKIP_BACKEND_VALIDATION=1
    - SOUTH_TESTS_MIGRATE=1
    - DJANGO_VERSION=">=1.6.11,<1.7"
    # node's version is pinned by .nvmrc and is autodetected by `nvm install`.
    - NODE_DIR="${HOME}/.nvm/versions/node/v$(< .nvmrc)"
    - YARN_VERSION="1.13.0"

script:
  # certain commands require sentry init to be run, but this is only true for
  # running things within Travis
  - make travis-test-$TEST_SUITE
  - make travis-scan-$TEST_SUITE
  # installing dependencies for after_* steps here ensures they get cached
  # since those steps execute after travis runs `store build cache`

after_success:
  - |
      coverage_files=$(ls .artifacts/*coverage.xml || true)
      if [[ -n "$coverage_files" || -f .artifacts/coverage/cobertura-coverage.xml ]]; then
        pip install codecov
        codecov -e TEST_SUITE
      fi

after_failure:
  - dmesg | tail -n 100

after_script:
  - npm install -g @zeus-ci/cli
  - zeus upload -t "text/xml+xunit" .artifacts/*junit.xml
  - zeus upload -t "text/xml+coverage" .artifacts/*coverage.xml
  - zeus upload -t "text/xml+coverage" .artifacts/coverage/cobertura-coverage.xml
  - zeus upload -t "text/html+pytest" .artifacts/*pytest.html
  - zeus upload -t "text/plain+pycodestyle" .artifacts/*pycodestyle.log
  - zeus upload -t "text/xml+checkstyle" .artifacts/*checkstyle.xml
  - zeus upload -t "application/webpack-stats+json" .artifacts/*webpack-stats.json

base_postgres: &postgres_default
  python: 2.7
  services:
    - memcached
    - redis-server
    - postgresql
  install:
    - python setup.py install_egg_info
    - pip install -e ".[dev,tests,optional]"
  before_script:
    - psql -c 'create database sentry;' -U postgres

# each job in the matrix inherits `env/global` and uses everything above,
# but custom `services`, `before_install`, `install`, and `before_script` directives
# may be defined to define and setup individual job environments with more precision.
matrix:
  fast_finish: true
  include:
    - <<: *postgres_default
      name: 'Backend [Postgres] (1/2)'
      env: TEST_SUITE=postgres DB=postgres TOTAL_TEST_GROUPS=2 TEST_GROUP=0
    - <<: *postgres_default
      name: 'Backend [Postgres] (2/2)'
      env: TEST_SUITE=postgres DB=postgres TOTAL_TEST_GROUPS=2 TEST_GROUP=1


    - env: TEST_SUITE=symbolicator

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/fa079cf6-8e6b-11e7-9155-0a580a28081c/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
